# Generated by Django 4.0.4 on 2022-05-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/avatars/default_avatar.jpg', upload_to='images/avatars/'),
        ),
    ]
