# Generated by Django 4.0.4 on 2022-05-14 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='priority',
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
