# Generated by Django 4.0.4 on 2022-05-17 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_remove_todoitem_priority_delete_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('medium', 'Medium'), ('high', 'High'), ('low', 'Low')], max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.priority'),
            preserve_default=False,
        ),
    ]
