# Generated by Django 4.0.4 on 2022-05-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_priority_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[('medium', 'Medium'), ('low', 'Low'), ('high', 'High')], default='low', max_length=6),
        ),
    ]
