# Generated by Django 4.0.4 on 2022-04-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_todoitem_completed_date_todoitem_task_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
