# Generated by Django 4.0.4 on 2022-05-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0004_priorities_todoitem_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priorities',
            name='setting',
            field=models.CharField(choices=[('h', 'high'), ('m', 'medium'), ('l', 'low')], max_length=1),
        ),
    ]
