# Generated by Django 4.0.5 on 2022-06-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default=True, max_length=300),
            preserve_default=False,
        ),
    ]
