# Generated by Django 4.0.5 on 2022-06-22 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_app', '0002_resource_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='projects',
            field=models.ManyToManyField(related_name='resources', to='study_app.project'),
        ),
    ]
