# Generated by Django 4.0.5 on 2022-06-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0002_rename_name_project_title_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
