# Generated by Django 4.0.5 on 2022-06-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0004_alter_project_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
