# Generated by Django 4.0.5 on 2022-06-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0006_project_is_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='projects',
            new_name='Subjects',
        ),
    ]
