# Generated by Django 4.0.5 on 2022-06-17 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0008_resource_date_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='Subjects',
            new_name='subjects',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='date_published',
        ),
    ]
