# Generated by Django 4.0.5 on 2022-06-17 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0010_resource_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='date_published',
        ),
    ]
