# Generated by Django 4.0.5 on 2022-06-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0012_resource_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='date_published',
            field=models.DateField(null=True),
        ),
    ]
