# Generated by Django 4.0.4 on 2022-05-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
