# Generated by Django 4.0.4 on 2022-05-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priority',
            old_name='todoitem',
            new_name='text',
        ),
    ]
