# Generated by Django 4.0.4 on 2022-05-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='Customuser',
            name='username',
            field=models.CharField(max_length=23, unique=True),
        ),
    ]
