# Generated by Django 4.0.4 on 2022-05-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_customuser_firstname_customuser_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
