# Generated by Django 4.0.4 on 2022-05-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
