# Generated by Django 4.0.4 on 2022-05-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('height', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
                ('image_front', models.CharField(max_length=300)),
                ('image_back', models.CharField(max_length=300)),
                ('urls', models.CharField(max_length=300)),
                ('types', models.ManyToManyField(related_name='pokemon', to='pokedex_app.pokemontype')),
            ],
        ),
    ]
